corrija de forma definitiva:
Error: In HTML, whitespace text nodes cannot be a child of <html>. Make sure you don't have any extra whitespace between tags on each line of your source code.
This will cause a hydration error.

  ...
    <HotReload assetPrefix="" globalError={[...]}>
      <AppDevOverlay state={{nextId:1, ...}} globalError={[...]}>
        <AppDevOverlayErrorBoundary globalError={[...]} onError={function bound dispatchSetState}>
          <ReplaySsrOnlyErrors>
          <DevRootHTTPAccessFallbackBoundary>
            <HTTPAccessFallbackBoundary notFound={<NotAllowedRootHTTPFallbackError>}>
              <HTTPAccessFallbackErrorBoundary pathname="/" notFound={<NotAllowedRootHTTPFallbackError>} ...>
                <RedirectBoundary>
                  <RedirectErrorBoundary router={{...}}>
                    <Head>
                    <link>
                    <script>
                    <script>
                    <script>
                    <RootLayout>
>                     <html lang="pt-BR" suppressHydrationWarning={true}>
>                       {" "}
                        ...
                    ...
        ...

    at createUnhandledError (https://6000-idx-studio-1746399134965.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:879:71)
    at handleClientError (https://6000-idx-studio-1746399134965.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1052:56)
    at console.error (https://6000-idx-studio-1746399134965.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1191:56)
    at validateTextNesting (https://6000-idx-studio-1746399134965.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:4071:174)
    at beginWork (https://6000-idx-studio-1746399134965.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:7833:211)
    at runWithFiberInDEV (https://6000-idx-studio-1746399134965.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:3501:74)
    at performUnitOfWork (https://6000-idx-studio-1746399134965.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10168:97)
    at workLoopConcurrentByScheduler (https://6000-idx-studio-1746399134965.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10164:58)
    at renderRootConcurrent (https://6000-idx-studio-1746399134965.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10146:71)
    at performWorkOnRoot (https://6000-idx-studio-1746399134965.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:9784:176)
    at performWorkOnRootViaSchedulerTask (https://6000-idx-studio-1746399134965.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:10796:9)
    at MessagePort.performWorkUntilDeadline (https://6000-idx-studio-1746399134965.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:1952:64)
    at html (<anonymous>)
    at RootLayout (rsc://React/Server/file:///home/user/studio/.next/server/chunks/ssr/%5Broot%20of%20the%20server%5D__bbf83bd0._.js?3:133:263)